export CUDA_VISIBLE_DEVICES=0,1,2    # 或者 0,1,2,3
export RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=1
export TRANSFORMERS_NO_ADVISORY_WARNINGS=1

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=../data/train/parquet/train_base_enzh_zhen.parquet \
    data.val_files=../data/test/parquet/test_base_enzh_zhen.parquet \
    data.train_batch_size=6 \
    data.max_prompt_length=256 \
    data.max_response_length=256 \
    data.filter_overlong_prompts=False \
    data.truncation='error' \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-3B \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.model.use_remove_padding=True \
    +actor_rollout_ref.model.torch_dtype=bfloat16 \
    +actor_rollout_ref.model.attn_implementation=eager \
    +critic.model.torch_dtype=bfloat16 \
    +critic.model.attn_implementation=eager \
    actor_rollout_ref.actor.ppo_mini_batch_size=6 \
    actor_rollout_ref.actor.ppo_micro_batch_size=6  \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=6 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.20 \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.ref.use_torch_compile=False \
    actor_rollout_ref.actor.use_torch_compile=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    algorithm.use_kl_in_reward=False \
    algorithm.kl_ctrl.kl_coef=0.0 \
    custom_reward_function.path=comet_reward_batch.py \
    reward_model.reward_manager=batch \
    trainer.val_before_train=False \
    trainer.logger=['wandb'] \
    trainer.project_name='qwen2.5_3b_grpo_mt' \
    trainer.experiment_name='qwen2.5_3b_r1-zero' \
    trainer.n_gpus_per_node=3 \
    trainer.nnodes=1 \
    trainer.save_freq=40 \
    trainer.test_freq=10 \
    trainer.val_before_train=False \
    trainer.default_local_dir=./results/qwen2.5_3b_r1-zero \
    trainer.total_epochs=1 $@ 2>&1 | tee /tmp/custom_grpo_fast.log
    # —— 强制所有模型用 eager 注意力 & bf16 —— 
    +actor_rollout_ref.model.attn_implementation=eager \
    +critic.model.attn_implementation=eager \
    +actor_rollout_ref.model.torch_dtype=bfloat16 \
    +critic.model.torch_dtype=bfloat16 \

    # —— vLLM 推理侧也用 bf16（与上面一致）——
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.ref.use_torch_compile=False \
    actor_rollout_ref.actor.use_torch_compile=False \
    critic.use_torch_compile=False \
    # 兜底（某些版本把 attn_implementation 放在更浅层）
    +actor_rollout_ref.attn_implementation=eager \
    +critic.attn_implementation=eager \
    +debug.print_config=true
    +actor_rollout_ref.model.torch_dtype=bfloat16
    +actor_rollout_ref.model.attn_implementation=flash_attention_2